// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SectraDataApp.Data;

#nullable disable

namespace SectraDataApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220505085007_AddSiteInfoToDatabase")]
    partial class AddSiteInfoToDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SectraDataApp.Models.SiteInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("cmpid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hostgroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nameofsoftware")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("root")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("versionpatch")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SiteInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
